// Code generated by \"ws-generator \"; PLEASE EDIT.
package ApiVersion

import "github.com/emicklei/go-restful"

type GolangType struct {
}

type Server struct {
	APIVersion string
	Resource   string
	Filters     []restful.FilterFunction
	Model      GolangType
	ModelList  []GolangType
}

func (s *Server) create(request *restful.Request, response *restful.Response) {

}

func (s *Server) get(request *restful.Request, response *restful.Response) {

}

func (s *Server) list(request *restful.Request, response *restful.Response) {

}

func (s *Server) update(request *restful.Request, response *restful.Response) {

}

func (s *Server) delete(request *restful.Request, response *restful.Response) {

}
