


// Code generated by \"ws-generator \"; NOT EDIT.
package ApiVersion

import (
	"fmt"
	"github.com/emicklei/go-restful-openapi"
	"net/http"

	"github.com/emicklei/go-restful"
)

func (s *Server) webService() *restful.WebService {

	ws := new(restful.WebService)

	ws.
		Path(fmt.Sprintf("/%s/%s/%s", APISPrefix, s.APIVersion, s.Resource)).
		Consumes(restful.MIME_XML, restful.MIME_JSON).
		Produces(restful.MIME_XML, restful.MIME_JSON)


	tags := []string{s.Resource}

	ws.Route(
		ws.GET("/").To(s.list). // service provider
		// build open-api doc
		Doc("get all {.Resource}}").
		Param().
		Metadata(restfulspec.KeyOpenAPITags, tags).
		Writes(s.Model).
		Returns(http.StatusOK, "OK", []GolangType{}).
		Returns(http.StatusNotFound, "Not Found", nil))

	return ws
}
